### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by mariumtapal** [baumer-lab/fec20#2]
@beanumber i am not able to enable Travis on this repo
<img width="1077" alt="Screen Shot 2020-11-18 at 23 24 56" src="https://user-images.githubusercontent.com/43043032/99621221-5386c680-29f5-11eb-963e-053cbef9cdb3.png">

**Comment by beanumber** [comment]
That's OK. Actually I guess the recommendation is to use GitHub Actions
instead.
