### ISSUE TITLE
expenditures sampled df is still too big

### ISSUE THREAD

**Issue by mariumtapal** [baumer-lab/fec20#3]
The expenditures df is 1.3MB for 1000 rows compared to only 40KB in `fec16` for the same number of rows. This causes the package to be > 5MB

**Comment by beanumber** [comment]
Wow. Any idea why it is so much bigger for the same number of rows? Are there new fields? There must be some image data in there or something.

**Comment by mariumtapal** [comment]
@beanumber There are no new fields and by inspection, I can't find anything. Do you know of a function/way I could look into it/detect image data?
